# Generated by Django 3.0.8 on 2021-06-10 02:44

import apps.log.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0082_delete_chat'),
        ('account', '0060_searchtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='clickLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=256, null=True, verbose_name='검색어')),
                ('created_at', models.DateTimeField(default=apps.log.models.time, verbose_name='등록일자')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='클라이언트')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Partner', verbose_name='파트너')),
            ],
            options={
                'verbose_name': '방문 로그',
                'verbose_name_plural': '방문 로그',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(null=True, verbose_name='채팅 내용')),
                ('user_type', models.IntegerField(blank=True, choices=[(0, '클라이언트'), (1, '파트너')], default=0, null=True, verbose_name='글쓴이 타입')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일자')),
                ('chat_type', models.IntegerField(choices=[(0, '텍스트'), (1, '이미지'), (2, '파일')], null=True, verbose_name='채팅 타입')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.log.models.chat_update_filename, verbose_name='채팅파일')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Answer', verbose_name='제안서')),
            ],
            options={
                'verbose_name': '채팅',
                'verbose_name_plural': '채팅',
            },
        ),
    ]
