# Generated by Django 3.0.8 on 2021-06-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20210610_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, null=True, verbose_name='검색어')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검색일자')),
            ],
            options={
                'verbose_name': '검색어 로그',
                'verbose_name_plural': '검색어 로그',
            },
        ),
    ]
