# Generated by Django 3.0.8 on 2021-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_searchtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtext',
            name='ip',
            field=models.CharField(max_length=256, null=True, verbose_name='ip'),
        ),
    ]
