# Generated by Django 3.0.8 on 2021-06-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_searchtext_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtext',
            name='ip',
        ),
    ]
