# Generated by Django 3.0.8 on 2021-06-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_remove_searchtext_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtext',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
