# Generated by Django 3.0.8 on 2021-01-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql = ["INSERT INTO category_develop VALUES(15,'수정해주세요',2,4);"],
            reverse_sql = ["DELETE FROM category_develop where category='수정해주세요';"]),
    ]
