# Generated by Django 3.0.8 on 2021-01-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210121_1716'),
        ('account', '0040_copyTablesql_20210114_1509'),
    ]

    operations = [
        migrations.RunSQL(
            sql = ["ALTER TABLE account_partner_history_set DROP CONSTRAINT account_partner_hist_subclass_id_39ab7e82_fk_category_"],
            reverse_sql = ["SELECT * FROM account_partner_history_set"]
        ),
        migrations.RunSQL(
            sql = ['DELETE FROM category_subclass'],
            reverse_sql = ['SELECT * FROM category_subclass']
            )
    ]
