# Generated by Django 3.0.8 on 2021-01-26 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project','0039_setnull_request_20210126_1326'),
        ('account', '0043_alter_constraint_partnercategory_20210126_1127'),
        ('category', '0003_auto_20210126_1146'),
    ]
    sqlCache = []
    reverseSqlCache = []

    categoryList=[
        ["소방용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["건설용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["도로용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["컴퓨터용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["주방용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["청소용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["생활/위생/욕실용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["가전용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["사무용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["배관용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["의료/헬스케어용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["자동차용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["레저/스포츠/여행용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["냉장고/에어컨/세탁기/청소기/TV","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["수유/유아용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["가구/인테리어/조명","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["반려동물용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["공작기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["유공압기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["냉난방/공조기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["화학/플랜트기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["밴딩/포장기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["식품기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["제어/계측기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["산업용로봇","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["검사기/시험기/실험기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["목공기계","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["농기계","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["중장비","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["특장차","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["물류시스템기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["운반/하역기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["산업환경장비","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["금형/사출기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["반도체장비","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["건설기기","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["펌프류","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["FA 부품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["동력전달 부품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["제어/계측 부품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["전자/반도체부품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["기타 기계 부품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["기타 부품 및 소재","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["씰링 부품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["베어링","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["볼트/너트/와샤/나사/스크류","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["방진/방음","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["전선/전기자재","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["건축자재","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["전동공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["충전공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["에어공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["용접공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["연마공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["엔진공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["유압공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["원예공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["절삭공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["측량공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["금형공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["공작공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
        ["자동차공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg",1],
    ]

    

    for category in categoryList:
        sqlCache.append(
            """
                insert into public."category_category"
                ("category", "middle_img","maincategory_id")
                values(
                    '{category}',
                    '{middle_img}',
                    '{maincategory_id}'
                );
            """.format(
                category = category[0],
                middle_img=category[1],
                maincategory_id=category[2],
                )
        )

    reverseSqlCache.append(
        """
            delete from public."category_category";
            ALTER SEQUENCE "category_category_id_seq" RESTART WITH 1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = reverseSqlCache,
            reverse_sql = sqlCache
            )
    ]
