# Generated by Django 3.0.8 on 2021-01-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210126_1143'),
    ]

    sqlCache = []
    reverseSqlCache = []

    categoryList=[
        ["제품 및 용품","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg"],
        ["기계설비","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg"],
        ["공구","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg"],
        ["스포츠례저","category/2020/4/16/9f7dd1e996084878bc37a4f0d7b6eb6f_category.jpg"],
    ]

    

    for category in categoryList:
        sqlCache.append(
            """
                insert into public."category_maincategory"
                ("maincategory", "big_img")
                values(
                    '{maincategory}',
                    '{big_img}'
                );
            """.format(
                maincategory = category[0],
                big_img=category[1]
                )
        )

    reverseSqlCache.append(
        """
            delete from public."category_maincategory";
            ALTER SEQUENCE "category_maincategory_id_seq" RESTART WITH 1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = reverseSqlCache,
            reverse_sql = sqlCache
            )
    ]
