# Generated by Django 3.0.8 on 2021-01-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210126_1417'),
    ]

    sqlCache = []
    reverseSqlCache = []

    categoryList=[
        ["제품 및 용품","media/null"],
        ["기계/설비/장비","media/null"],
        ["부품 및 소재","media/null"],
        ["공구류","media/null"],
    ]

    

    for category in categoryList:
        sqlCache.append(
            """
                insert into public."category_maincategory"
                ("maincategory", "big_img")
                values(
                    '{maincategory}',
                    '{big_img}'
                );
            """.format(
                maincategory = category[0],
                big_img=category[1]
                )
        )

    reverseSqlCache.append(
        """
            delete from public."category_maincategory";
            ALTER SEQUENCE "category_maincategory_id_seq" RESTART WITH 1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = sqlCache,
            reverse_sql = reverseSqlCache
            )
    ]
