# Generated by Django 3.0.8 on 2021-01-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20210126_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='period',
            field=models.CharField(default='0', max_length=256, verbose_name='기간정보'),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.CharField(default='0', max_length=256, verbose_name='가격정보'),
        ),
    ]
