# Generated by Django 3.0.8 on 2021-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20210126_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='additionalPrice',
            field=models.CharField(default='0', max_length=256, verbose_name='추가금액'),
        ),
    ]
