# Generated by Django 3.0.8 on 2021-04-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_auto_20210414_2208'),
        ('category', '0011_auto_20210219_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
