# Generated by Django 2.1.1 on 2020-04-22 04:53

import apps.board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='content',
        ),
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.board.models.magazine_update_filename, verbose_name='매거진 이미지'),
        ),
    ]
