# Generated by Django 2.1.1 on 2020-06-02 05:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200422_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='link',
        ),
        migrations.AddField(
            model_name='magazine',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
