# Generated by Django 3.0.8 on 2020-11-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200602_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='summary',
            field=models.TextField(null=True, verbose_name='링크'),
        ),
    ]
