# Generated by Django 3.0.8 on 2020-11-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_magazine_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='summary',
            field=models.TextField(null=True, verbose_name='요약'),
        ),
    ]
