# Generated by Django 3.0.8 on 2021-03-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20201123_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='category',
            field=models.CharField(default='기본', max_length=40, verbose_name='매거진 분류'),
        ),
    ]
