# Generated by Django 3.0.8 on 2021-04-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_magazine_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
