# Generated by Django 3.0.8 on 2021-04-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_delete_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='category',
        ),
        migrations.CreateModel(
            name='Magazine_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='기본', max_length=40, verbose_name='매거진 분류')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Magazine', verbose_name='매거진')),
            ],
            options={
                'verbose_name': '   매거진 카테고리',
                'verbose_name_plural': '   매거진 카테고리',
            },
        ),
    ]
