# Generated by Django 3.0.8 on 2021-04-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20210427_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine_category',
            name='magazine',
        ),
        migrations.AddField(
            model_name='magazine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Magazine_Category', verbose_name='매거진 카테고리'),
        ),
    ]
