# Generated by Django 2.1.1 on 2020-04-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sendkakao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=0, verbose_name='메세지 전송결과')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='메세지 전송 결과 상세')),
                ('refkey', models.CharField(max_length=100, null=True, verbose_name='레퍼런스키')),
                ('messagekey', models.CharField(max_length=100, null=True, verbose_name='메세지키')),
            ],
            options={
                'verbose_name': '     카카오톡',
                'verbose_name_plural': '     카카오톡',
            },
        ),
    ]
