# Generated by Django 3.0.8 on 2021-01-06 06:26

import apps.project.models
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰제품명')),
                ('price', models.CharField(blank=True, max_length=256, null=True, verbose_name='희망비용')),
                ('day', models.CharField(blank=True, max_length=256, null=True, verbose_name='희망프로젝트기간(일)')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='의뢰내용')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.project.models.request_update_filename, verbose_name='의뢰파일')),
            ],
            options={
                'verbose_name': '     공통질문',
                'verbose_name_plural': '     공통질문',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '     프로젝트',
                'verbose_name_plural': '     프로젝트',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰제품명')),
                ('price', models.CharField(blank=True, max_length=256, null=True, verbose_name='희망비용')),
                ('day', models.CharField(blank=True, max_length=256, null=True, verbose_name='희망프로젝트기간(일)')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='의뢰내용')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.project.models.request_update_filename, verbose_name='의뢰파일')),
                ('created_at', models.DateTimeField(default=apps.project.models.time, verbose_name='등록일자')),
                ('send_information', models.BooleanField(default=False, null=True, verbose_name='의뢰서 정보 카카오톡 발송 여부')),
                ('active_save', models.BooleanField(default=True, null=True, verbose_name='활성 변화 저장')),
                ('progress_status', models.CharField(blank=True, choices=[('미정', '미정'), ('드랍', '드랍'), ('진행중', '진행중'), ('전환', '전환')], default='미정', max_length=10, null=True, verbose_name='진행현황')),
                ('explain', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('estimate', models.IntegerField(blank=True, default=0, null=True, verbose_name='견적')),
                ('partner_estimate', models.TextField(blank=True, null=True, verbose_name='파트너(견적)')),
                ('transfer_money', models.CharField(choices=[('아니오', '아니오'), ('선금입금', '선금입금'), ('완납', '완납')], default='아니오', max_length=10, verbose_name='입금 여부')),
                ('category', models.ManyToManyField(to='category.Develop', verbose_name='의뢰분야')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='작성클라이언트')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Subclass', verbose_name='의뢰제품')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '     요청된 의뢰',
                'verbose_name_plural': '     요청된 의뢰',
            },
        ),
        migrations.CreateModel(
            name='Select_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=256, null=True, verbose_name='선택질문')),
                ('answer', models.CharField(blank=True, max_length=256, null=True, verbose_name='선택질문답변')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Develop', verbose_name='개발분야')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Request', verbose_name='의뢰서')),
            ],
            options={
                'verbose_name': '     의뢰서에 저장되는 선택질문/답변',
                'verbose_name_plural': '     의뢰서에 저장되는 선택질문/답변',
            },
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(blank=True, null=True, verbose_name='선택질문')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Develop', verbose_name='개발분야중분류')),
            ],
            options={
                'verbose_name': '     선택질문',
                'verbose_name_plural': '     선택질문',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='가격 만족도')),
                ('time_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='업무속도 및 납기')),
                ('talk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='의사소통')),
                ('expert_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='전문성')),
                ('result_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='결과물 및 품질')),
                ('content_good', models.TextField(blank=True, null=True, verbose_name='미팅 후기')),
                ('content_bad', models.TextField(blank=True, null=True, verbose_name='계약 후기')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='작성클라이언트')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Partner', verbose_name='파트너')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '리뷰별점',
                'verbose_name_plural': '리뷰별점',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.CharField(blank=True, max_length=256, null=True, verbose_name='컨텐츠1')),
                ('content2', models.CharField(blank=True, max_length=256, null=True, verbose_name='컨텐츠2')),
                ('content3', models.CharField(blank=True, max_length=256, null=True, verbose_name='컨텐츠3')),
                ('content4', models.CharField(blank=True, max_length=256, null=True, verbose_name='컨텐츠4')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Select', verbose_name='선택질문')),
            ],
            options={
                'verbose_name': '     선택질문컨텐츠',
                'verbose_name_plural': '     선택질문컨텐츠',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True, verbose_name='개발 분야')),
                ('people', models.TextField(blank=True, null=True, verbose_name='개발 투입 인원')),
                ('price', models.TextField(blank=True, null=True, verbose_name='개발 입률')),
                ('strategy', models.TextField(blank=True, null=True, verbose_name='예상 개발 기능')),
                ('period', models.TextField(blank=True, null=True, verbose_name='예상 개발 기간')),
                ('day', models.IntegerField(default=0, verbose_name='총 개발 기간')),
                ('all_price', models.IntegerField(default=0, verbose_name='예상 견적')),
                ('expert', models.TextField(blank=True, null=True, verbose_name='전문성 및 경험')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.project.models.answer_update_filename, verbose_name='의뢰파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('state', models.IntegerField(choices=[(0, 'NOTSUBMIT'), (1, 'YES'), (2, 'NO')], default=0, verbose_name='미팅 상태')),
                ('active', models.BooleanField(default=False, verbose_name='활성화여부')),
                ('open_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='제안서 오픈 시간')),
                ('send_meeting', models.BooleanField(default=False, verbose_name='미팅 안내 카톡 전송 여부')),
                ('info_check', models.IntegerField(blank=True, choices=[(0, '정보 미확인'), (1, '파트너사 정보 확인'), (2, '파트너사 연락')], default=0, null=True, verbose_name='정보확인여부')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='클라이언트')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Partner', verbose_name='작성 파트너')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '     제안서',
                'verbose_name_plural': '     제안서',
            },
        ),
    ]
