# Generated by Django 3.0.8 on 2021-01-06 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210106_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='day',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='send_information',
            new_name='sendInformation',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='request',
            name='active_save',
        ),
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
        # migrations.RemoveField(
        #     model_name='request',
        #     name='content',
        # ),
        migrations.RemoveField(
            model_name='request',
            name='estimate',
        ),
        # migrations.RemoveField(
        #     model_name='request',
        #     name='explain',
        # ),
        migrations.RemoveField(
            model_name='request',
            name='partner_estimate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='progress_status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='transfer_money',
        ),
    ]
