# Generated by Django 3.0.8 on 2021-01-06 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='review',
            name='isMain',
            field=models.BooleanField(default=False, verbose_name='메인 페이지 노출 여부'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='제목'),
        ),
    ]
