# Generated by Django 3.0.8 on 2021-01-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210106_1738'),
        ('project', '0003_auto_20210106_1718'),
    ]

    operations = [
    ]
