# Generated by Django 3.0.8 on 2021-01-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210106_1759'),
        ('project', '0003_merge_20210106_1746'),
    ]

    operations = [
    ]
