# Generated by Django 3.0.8 on 2021-01-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_consultantportfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultantportfolio',
            options={'verbose_name': '     컨설턴트포트폴리오', 'verbose_name_plural': '     컨설턴트포트폴리오'},
        ),
    ]
