# Generated by Django 3.0.8 on 2021-01-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('project', '0008_auto_20210106_1908'),
    ]

    operations = [
        migrations.RunSQL(
            sql = ['UPDATE project_request SET product_id = 50;'],
            reverse_sql = ['UPDATE project_request SET product_id = 40;']),
        migrations.AlterField(
            model_name='request',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='의뢰제품'),
        ),
    ]
