# Generated by Django 3.0.8 on 2021-01-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_request_alter_product_20210107_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Proposal', verbose_name='견적서'),
        ),
    ]
