# Generated by Django 3.0.8 on 2021-01-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_request_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposalType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProposalType', verbose_name='견적서타입'),
        ),
    ]
