# Generated by Django 3.0.8 on 2021-01-08 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_proposal_20210108_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='proposal',
        ),
        migrations.AddField(
            model_name='proposal',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='프로젝트'),
        ),
    ]
