# Generated by Django 3.0.8 on 2021-01-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_proposaltype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
            ],
        ),
    ]
