# Generated by Django 3.0.8 on 2021-01-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_kakaotoken_20210112_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakaotoken',
            name='token',
            field=models.CharField(max_length=256),
        ),
    ]
