# Generated by Django 3.0.8 on 2021-01-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_kakaotoken_20210113_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakaotoken',
            name='token',
            field=models.TextField(),
        ),
    ]
