# Generated by Django 3.0.8 on 2021-01-19 03:30

import apps.project.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_task_showname_202101138_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.project.models.request_update_filename, verbose_name='의뢰파일')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Request', verbose_name='의뢰서')),
            ],
            options={
                'verbose_name': '     제품 기본정보 첨부파일',
                'verbose_name_plural': '     제품 기본정보 첨부파일',
            },
        ),
    ]
