# Generated by Django 3.0.8 on 2021-01-19 07:44

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_request_data_20210119_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.project.models.request_update_filename, verbose_name='의뢰파일'),
        ),
    ]
