# Generated by Django 3.0.8 on 2021-01-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_requestFile_alter_20210119_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='분류'),
        ),
    ]
