# Generated by Django 3.0.8 on 2021-01-20 03:25

from django.db import migrations
from dotenv import load_dotenv
import os
load_dotenv()
from ..models import *
import requests
import json

class Migration(migrations.Migration):
    def getToken(apps, schema_editor):
        if os.getenv('DB_NAME') == 'boltnnutplatform2':
            url = 'https://api.bizppurio.com/v1/token'
            headers = {
                'Content-type': 'application/json;charset=utf-8', 
                'Accept': 'text/plain', 
                'Authorization':'Basic Ym9sdG5udXRfa29yZWE6QGJvbHQxMjM='
            }
            response = requests.post(url, headers=headers)
            response = json.loads(response.content)
            token = response['accesstoken']
            tokenType = response['type']
            basicAccessToken = tokenType + " " + token
            data = KakaoToken.objects.get()
            data.token = basicAccessToken
            data.save()
        else:
            print("donothing")
            pass

    dependencies = [
        ('project', '0023_task_add_20210119_1658'),
    ]

    operations = [
        migrations.RunSQL(
            sql = ["DELETE FROM project_kakaotoken; INSERT INTO project_kakaotoken VALUES(1,'asdf');"],
            reverse_sql = ['DELETE FROM project_kakaotoken']
        ),
        migrations.RunPython(getToken, reverse_code = migrations.RunPython.noop),
    ]
