# Generated by Django 3.0.8 on 2021-01-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_add_task_20210120_1748'),
    ]

    sqlCache = []
    reverseSqlCache = []

    proposalTypeList=[
        ["2000","30","Software개발/시중제품/디자인미변경"],
        ["2500","30","Software개발/시중제품/디자인변경"],
        ["3000","30","Software개발/시중제품/기능 변경"],
        ["3200","30","Software개발/시중제품/신제품 개발"],
        ["1500","30","Software미개발/시중제품/디자인미변경"],
        ["1800","30","Software미개발/시중제품/디자인변경"],
        ["2000","30","software미개발/시중제품/기능변경"],
        ["2500","","Software미개발/신제품"],
        ["300","","특수설계/기존제품/디자인미변경"],
        ["500","","특수설계/기존제품/디자인변경"],
        ["700","","특수설계/기존제품 기능 변경/디자인변경"],
        ["150","","일반설계/기존제품/디자인미변경"],
        ["350","","일반설계/기존제품/디자인변경"],
        ["550","","일반설계/신제품/디자인변경"]
    ]

    

    for proposalType in proposalTypeList:
        sqlCache.append(
            """
                insert into public."project_proposaltype"
                ("price", "period","name")
                values(
                    '{price}',
                    '{period}',
                    '{name}'
                );
            """.format(
                price = proposalType[0],
                period=proposalType[1],
                name=proposalType[2],
                )
        )

    reverseSqlCache.append(
        """
            delete from public."project_proposaltype";
            ALTER SEQUENCE "project_proposaltype_id_seq" RESTART WITH 1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = reverseSqlCache, 
            reverse_sql = reverseSqlCache
        ),
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
