# Generated by Django 3.0.8 on 2021-01-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_add_manager_status_20210121_1528'),
    ]

    sqlCache = []
    reverseSqlCache = []

    statusList=["수정해주세요","전화(1차)","전화(2차)","전화(3차)","업체수배","상담","가견적제공","미팅"]

    

    for status in statusList:
        sqlCache.append(
            """
                insert into public."project_projectstatus"
                ("name")
                values(
                    '{name}'
                );
            """.format(
                name = status,
                )
        )

    reverseSqlCache.append(
        """
            delete from public."project_projectstatus";
            ALTER SEQUENCE "project_projectstatus_id_seq" RESTART WITH 1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = reverseSqlCache, 
            reverse_sql = reverseSqlCache
        ),
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]