# Generated by Django 3.0.8 on 2021-01-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_alter_meta_manager_20210121_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': '     프로젝트담당자', 'verbose_name_plural': '     프로젝트담당자'},
        ),
    ]
