# Generated by Django 3.0.8 on 2021-01-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_alter_meta_20210121_1629'),
    ]
    
    sqlCache = []
    reverseSqlCache = []

    managerList=["수정해주세요","노현수"]

    for manager in managerList:
        sqlCache.append(
            """
                insert into public."project_manager"
                ("name")
                values(
                    '{name}'
                );
            """.format(
                name = manager,
                )
        )

    reverseSqlCache.append(
        """
            delete from public."project_manager";
            ALTER SEQUENCE "project_manager_id_seq" RESTART WITH 1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = reverseSqlCache, 
            reverse_sql = reverseSqlCache
        ),
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
