# Generated by Django 3.0.8 on 2021-01-26 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category', verbose_name='의뢰제품'),
        ),
    ]
