# Generated by Django 3.0.8 on 2021-01-26 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_alter_contstraint_20210126_1056'),
    ]

    operations = [
        migrations.RunSQL(
            sql = ['ALTER TABLE project_request ALTER COLUMN product_id DROP NOT NULL;'],
            reverse_sql = ['ALTER TABLE project_request ALTER COLUMN product_id SET NOT NULL;']
        ),
    ]
