# Generated by Django 3.0.8 on 2021-01-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_setnull_request_20210126_1326'),
    ]

    sqlCache = []
    reverseSqlCache = []

    proposalTypeList=[
        ["0","0","default"],
        ["0","0","도면입력타입"]
    ]

    for proposalType in proposalTypeList:
        sqlCache.append(
            """
                insert into public."project_proposaltype"
                ("price", "period","name")
                values(
                    '{price}',
                    '{period}',
                    '{name}'
                );
            """.format(
                price = proposalType[0],
                period=proposalType[1],
                name=proposalType[2],
                )
        )

    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = ['SELECT * FROM project_proposaltype']
        )
    ]
