# Generated by Django 3.0.8 on 2021-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_add_proposal_20210127_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaltype',
            name='task',
            field=models.ManyToManyField(related_name='task', to='project.Task', verbose_name='타입별세부일정'),
        ),
    ]
