# Generated by Django 3.0.8 on 2021-01-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_alter_relatedName_20210127_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='프로젝트'),
        ),
    ]
