# Generated by Django 3.0.8 on 2021-01-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_alter_project_20210129_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '     요청사항', 'verbose_name_plural': '     요청사항'},
        ),
    ]
