# Generated by Django 3.0.8 on 2021-02-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_alter_meta_comment_20210129_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Comment', verbose_name='상위댓글'),
        ),
    ]
