# Generated by Django 3.0.8 on 2021-02-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_alter_comment_parent_20210201_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
