# Generated by Django 3.0.8 on 2021-02-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_alter_review_20210201_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content_bad',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content_good',
        ),
        migrations.RemoveField(
            model_name='review',
            name='expert_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='review',
            name='price_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='result_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='talk_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='time_score',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
    ]
