# Generated by Django 3.0.8 on 2021-02-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_renew_review_20210201_1507'),
    ]
    sqlCache = []
    reverseSqlCache = []

    proposalTypeList=[
        ["20000000","15","Software개발/시중제품/디자인미변경"],
        ["25000000","15","Software개발/시중제품/디자인변경"],
        ["30000000","15","Software개발/시중제품/기능변경"],
        ["32000000","15","Software개발/시중제품/신제품개발"],
        ["15000000","15","Software미개발/시중제품/디자인미변경"],
        ["18000000","15","Software미개발/시중제품/디자인변경"],
        ["20000000","15","software미개발/시중제품/기능변경"],
        ["25000000","15","Software미개발/신제품"],
        ["3000000","9","특수설계/기존제품/디자인미변경"],
        ["5000000","10","특수설계/기존제품/디자인변경"],
        ["7000000","10","특수설계/기존제품/기능변경/디자인변경"],
        ["1500000","9","일반설계/기존제품/디자인미변경"],
        ["3500000","8","일반설계/기존제품/디자인변경"],
        ["5500000","10","일반설계/신제품/디자인변경"],
        ["7000000","10","특수설계/신제품/기능변경/디자인변경"],
        ["4500000","8","일반설계/기존제품/디자인변경/기능변경"],
        ["0","0","default"],
        ["0","0","도면입력타입"],
    ]

    

    for proposalType in proposalTypeList:
        sqlCache.append(
            """
                insert into public."project_proposaltype"
                ("price", "period","name")
                values(
                    '{price}',
                    '{period}',
                    '{name}'
                );
            """.format(
                price = proposalType[0],
                period=proposalType[1],
                name=proposalType[2],
                )
        )

    reverseSqlCache.append(
        """
            delete from public."project_proposaltype";
            ALTER SEQUENCE "project_proposaltype_id_seq" RESTART WITH 1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = reverseSqlCache, 
            reverse_sql = reverseSqlCache
        ),
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
    