# Generated by Django 3.0.8 on 2021-02-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_modify_proposal_type_task_20210202_1357'),
    ]

    operations = [
        migrations.RunSQL(
            sql = ["UPDATE project_proposaltype SET period ='10' WHERE period='8'"], 
            reverse_sql = ["UPDATE project_proposaltype SET period ='10' WHERE period='8'"]
        )
    ]
