# Generated by Django 3.0.8 on 2021-02-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20210126_1441'),
        ('project', '0052_create_projectFile_20210204_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='content',
        ),
        migrations.RemoveField(
            model_name='request',
            name='explain',
        ),
        migrations.AlterField(
            model_name='request',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category', verbose_name='카테고리'),
        ),
    ]
