# Generated by Django 3.0.8 on 2021-02-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_auto_20210215_1817'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='proposaltype',
        #     name='additionalPrice',
        #     field=models.CharField(default='0', max_length=256, verbose_name='추가금액'),
        # ),
    ]
