# Generated by Django 3.0.8 on 2021-02-16 04:26

from django.db import migrations
from api.account.serializers import *
from ..models import *

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_auto_20210216_1124'),
    ]

    def addProposalType(apps, schema_editor):
        ProposalType.objects.create(
            name = "견적서확인단계까지왔지만견적서확인못한타입",
            price = "0",
            period = "0",
            )
        


    operations = [
        migrations.RunPython(addProposalType, reverse_code = migrations.RunPython.noop),
    ]