# Generated by Django 3.0.8 on 2021-02-17 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_auto_20210217_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposalType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='project.ProposalType', verbose_name='견적서타입'),
        ),
    ]
