# Generated by Django 3.0.8 on 2021-02-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_project_progressstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progressStep',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=10, verbose_name='고객 진행 단계'),
        ),
    ]
