# Generated by Django 3.0.8 on 2021-02-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0061_auto_20210217_1455'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='proposaltype',
        #     name='additionalPrice',
        # ),
    ]
