# Generated by Django 3.0.8 on 2021-04-14 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_auto_20210414_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일'),
        ),
    ]
