# Generated by Django 3.0.8 on 2021-04-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_auto_20210419_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='file_close',
        ),
        migrations.RemoveField(
            model_name='request',
            name='file_open',
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.IntegerField(choices=[(0, '텍스트'), (1, '이미지'), (2, '파일')], max_length=256, null=True, verbose_name='채팅 타입'),
        ),
    ]
