# Generated by Django 3.0.8 on 2021-04-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_auto_20210426_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='check_time',
        ),
        migrations.AddField(
            model_name='answer',
            name='check_time_client',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='파트너 제안서 최종 확인 시간'),
        ),
    ]
