# Generated by Django 3.0.8 on 2021-04-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_auto_20210426_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='check_time_client',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='check_time_partner',
        ),
    ]
