# Generated by Django 3.0.8 on 2021-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0072_auto_20210426_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='check_time_client',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='check_time_partner',
        ),
    ]
