# Generated by Django 3.0.8 on 2021-04-28 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0073_auto_20210427_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='check_time_client',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='클라이언트 확인 시간'),
        ),
        migrations.AddField(
            model_name='answer',
            name='check_time_partner',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='파트너 확인 시간'),
        ),
    ]
