# Generated by Django 3.0.8 on 2021-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_auto_20210428_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='price',
            field=models.IntegerField(blank=True, max_length=256, null=True, verbose_name='희망비용'),
        ),
    ]
