# Generated by Django 3.0.8 on 2021-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0075_auto_20210430_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='희망비용'),
        ),
    ]
