# Generated by Django 3.0.8 on 2021-05-03 06:25

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0076_auto_20210430_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.project.models.chat_update_filename, verbose_name='채팅파일'),
        ),
    ]
