# Generated by Django 3.0.8 on 2021-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0077_chat_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('모집중', '모집중'), ('모집종료', '모집종료')], default='모집중', max_length=10, null=True, verbose_name='프로젝트 상태'),
        ),
    ]
