# Generated by Django 3.0.8 on 2021-05-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0078_auto_20210506_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='order_request_close',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='비공개 발주 요청사항'),
        ),
        migrations.AlterField(
            model_name='request',
            name='order_request_open',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='공개 발주 요청사항'),
        ),
    ]
