# Generated by Django 3.0.8 on 2021-05-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0079_auto_20210507_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='고객 의뢰 이유'),
        ),
    ]
