# Generated by Django 3.0.8 on 2021-06-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0081_auto_20210609_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
