# Generated by Django 3.0.8 on 2021-01-06 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startAt', models.DateTimeField(verbose_name='시작시각')),
                ('endAt', models.DateTimeField(verbose_name='종료시각')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('note', models.TextField(null=True, verbose_name='메모')),
                ('status', models.BooleanField(verbose_name='상태')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Request', verbose_name='의뢰서')),
            ],
            options={
                'verbose_name': '     스케쥴',
                'verbose_name_plural': '     스케쥴',
            },
        ),
    ]
