# Generated by Django 3.0.8 on 2021-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isOnline',
            field=models.BooleanField(default=False, verbose_name='온라인미팅'),
        ),
    ]
