# Generated by Django 2.1.1 on 2020-04-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200416_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='meeting',
            field=models.IntegerField(default=0, null=True, verbose_name='미팅 전환율'),
        ),
    ]
