# Generated by Django 2.1.1 on 2020-04-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_partner_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='fail',
            field=models.IntegerField(default=0, null=True, verbose_name='미팅 실패'),
        ),
        migrations.AddField(
            model_name='partner',
            name='success',
            field=models.IntegerField(default=0, null=True, verbose_name='미팅 성공'),
        ),
    ]
