# Generated by Django 2.1.1 on 2020-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200423_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='meeting',
            field=models.FloatField(default=0, null=True, verbose_name='미팅 전환율'),
        ),
    ]
