# Generated by Django 2.1.1 on 2020-05-06 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200423_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_class', models.IntegerField(default=0, null=True, verbose_name='클라이언트 클래스')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('payment', models.IntegerField(default=0, null=True, verbose_name='클래스 유지 일자')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='클라이언트')),
            ],
            options={
                'verbose_name': '클라이언트 클래스',
                'verbose_name_plural': '클라이언트 클래스',
            },
        ),
    ]
