# Generated by Django 2.1.1 on 2020-05-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_clientclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientclass',
            name='payment',
            field=models.IntegerField(default=0, null=True, verbose_name='클래스 종료 일자'),
        ),
    ]
