# Generated by Django 2.1.1 on 2020-05-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200510_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientclass',
            name='payment',
        ),
        migrations.AddField(
            model_name='clientclass',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='클래스 종료 일자'),
        ),
    ]
