# Generated by Django 2.1.1 on 2020-05-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200510_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='coin',
            field=models.IntegerField(default=5000, null=True, verbose_name='코인'),
        ),
    ]
