# Generated by Django 2.1.1 on 2020-05-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200512_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='coin',
            field=models.IntegerField(default=2000, null=True, verbose_name='코인'),
        ),
    ]
