# Generated by Django 2.1.1 on 2020-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200512_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_partner',
            field=models.BooleanField(default=True, null=True, verbose_name='파트너여부'),
        ),
    ]
