# Generated by Django 2.1.1 on 2020-06-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_marketing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='possible_set',
        ),
    ]
