# Generated by Django 2.1.1 on 2020-06-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_partner_possible_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='로그인일자')),
                ('type', models.IntegerField(choices=[(0, 'CLIENT'), (1, 'PARTNER')], default=0, verbose_name='유저타입')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': '로그인 로그',
                'verbose_name_plural': '로그인 로그',
                'ordering': ('-created_at',),
            },
        ),
    ]
