# Generated by Django 2.1.1 on 2020-06-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientclass',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='업체명'),
        ),
        migrations.AddField(
            model_name='clientclass',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='직급'),
        ),
    ]
