# Generated by Django 2.1.1 on 2020-06-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200622_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, null=True, verbose_name='방문경로')),
            ],
            options={
                'verbose_name': '방문경로',
                'verbose_name_plural': '방문경로',
            },
        ),
    ]
