# Generated by Django 3.0.8 on 2020-07-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200622_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='최근 활동'),
        ),
    ]
