# Generated by Django 3.0.8 on 2020-07-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='업종')),
            ],
            options={
                'verbose_name': '업종',
                'verbose_name_plural': '업종',
            },
        ),
    ]
