# Generated by Django 3.0.8 on 2020-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=256, null=True, verbose_name='업종')),
            ],
            options={
                'verbose_name': '업종',
                'verbose_name_plural': '업종',
            },
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
