# Generated by Django 3.0.8 on 2020-07-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200728_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business',
            field=models.CharField(max_length=256, null=True, verbose_name='업종'),
        ),
    ]
