# Generated by Django 3.0.8 on 2020-08-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_client_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='real_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='휴대폰 번호'),
        ),
    ]
