# Generated by Django 3.0.8 on 2020-09-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200908_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='grade',
            field=models.IntegerField(default=0, null=True, verbose_name='파트너 등급'),
        ),
    ]
