# Generated by Django 3.0.8 on 2020-09-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('account', '0030_auto_20200908_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='진행한 제품들'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='history_set',
            field=models.ManyToManyField(null=True, related_name='history_product', to='category.Subclass', verbose_name='진행한제품들(history로 대체)'),
        ),
    ]
