# Generated by Django 3.0.8 on 2020-09-28 02:38

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20200928_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.account.models.partner_update_filename, verbose_name='이력서'),
        ),
    ]
