# Generated by Django 3.0.8 on 2021-01-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_partner_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='grade',
            field=models.IntegerField(choices=[], default=0, null=True, verbose_name='파트너 등급'),
        ),
    ]
