# Generated by Django 3.0.8 on 2021-01-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20210106_1526'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='partner',
        #     name='history_set',
        # ),
    ]
