#-*- coding: cp949 -*-
# Generated by Django 3.0.8 on 2021-01-06 09:58

from django.db import migrations
from dotenv import load_dotenv
import os
load_dotenv()


class Migration(migrations.Migration):
    def backup (apps, schema_editor):
        DATABASE_NAME = os.getenv('DB_NAME')
        DATABSE_USER = os.getenv('DB_USER')
        DATABSE_PASSWORD = os.getenv('DB_PASSWORD')
        DATABASE_HOST = os.getenv('DB_HOST')
        DATABSE_PORT = os.getenv('DB_PORT')
        os.system("PGPASSWORD=" + DATABSE_PASSWORD + " pg_dump -Fc -h " + DATABASE_HOST + " -U " + DATABSE_USER + " -d " + DATABASE_NAME + " -f ./apps/account/migrations/0035_client_data_20210107_1155_backup.tar -v")

    def restore (apps, schema_editor):
        DATABASE_NAME = os.getenv('DB_NAME')
        DATABSE_USER = os.getenv('DB_USER')
        DATABSE_PASSWORD = os.getenv('DB_PASSWORD')
        DATABASE_HOST = os.getenv('DB_HOST')
        DATABSE_PORT = os.getenv('DB_PORT')
        #os.system("PGPASSWORD="+ DATABSE_PASSWORD + " pg_restore -h " + DATABASE_HOST + " -U " + DATABSE_USER + " -d " + DATABASE_NAME + " -c -n public -Fc ./apps/account/migrations/0035_client_data_20210107_1155_backup.tar -v")
        #TO DO:// 자동으로 resotre 까지 하게 만들기
    dependencies = [
        ('account', '0034_remove_partner_history_set'),
    ]

    operations = [
        migrations.RunPython(backup, reverse_code= restore),
        migrations.RunSQL(
            sql = [("""
                UPDATE account_user 
                SET phone = ''
                FROM (
                    SELECT u.phone as phone, count(phone)as cnt
                    FROM account_user as u, account_client c
                    WHERE u.id = c.id and is_superuser = false and is_staff = false
                    GROUP by phone
                    HAVING count(phone) >=2
                ) AS duplicated_phone
                WHERE account_user.phone  = duplicated_phone.phone;            
            """)],
            reverse_sql = [("Select id from account_user;")]            
        )
    ]

