# Generated by Django 3.0.8 on 2021-01-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_client_data_20210107_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimateType', models.IntegerField(verbose_name='표준견적 타입')),
                ('price', models.CharField(max_length=256, verbose_name='가격')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Partner', verbose_name='파트너')),
            ],
            options={
                'verbose_name': '파트너 표준 가격',
                'verbose_name_plural': '파트너 표준 가격',
            },
        ),
    ]
