# Generated by Django 3.0.8 on 2021-01-15 06:31

from django.db import migrations
from dotenv import load_dotenv
import os
load_dotenv()
from django.utils import timezone

class Migration(migrations.Migration):

    def backup (apps, schema_editor):
        DATABASE_NAME = os.getenv('DB_NAME')
        DATABSE_USER = os.getenv('DB_USER')
        DATABSE_PASSWORD = os.getenv('DB_PASSWORD')
        DATABASE_HOST = os.getenv('DB_HOST')
        DATABSE_PORT = os.getenv('DB_PORT')
        os.system("PGPASSWORD=" + DATABSE_PASSWORD + " pg_dump -h " + DATABASE_HOST + " -U " + DATABSE_USER + " -d boltnnutplatform2 -t account_partner_history_set -F t -f ./apps/account/migrations/partner_history.tar -v")


    def restore (apps, schema_editor):
        DATABASE_NAME = os.getenv('DB_NAME')
        DATABSE_USER = os.getenv('DB_USER')
        DATABSE_PASSWORD = os.getenv('DB_PASSWORD')
        DATABASE_HOST = os.getenv('DB_HOST')
        DATABSE_PORT = os.getenv('DB_PORT')
        os.system("PGPASSWORD="+ DATABSE_PASSWORD + " pg_restore -h " + DATABASE_HOST + " -U " + DATABSE_USER + " -d " + DATABASE_NAME + " -t account_partner_history_set -a -F t ./apps/account/migrations/partner_history.tar -v")

    def doNothing(apps, schema_editor):
        pass

    dependencies = [
        ('account', '0036_partnerEstimate_create_20210117_1527'),
    ]

    operations = [
        # migrations.RunPython(backup, reverse_code= doNothing),
        # migrations.RunSQL(
        #     sql = ['CREATE TABLE account_partner_history_set( id INTEGER PRIMARY KEY, partner_id INTEGER NOT NULL, subclass_id INTEGER NOT NULL)'],
        #     reverse_sql = ['DROP TABLE account_partner_history_set']),
    ]
