# Generated by Django 3.0.8 on 2021-01-15 08:06

from django.db import migrations
from dotenv import load_dotenv
import os
load_dotenv()

class Migration(migrations.Migration):

    def restore (apps, schema_editor):
        DATABASE_NAME = os.getenv('DB_NAME')
        DATABSE_USER = os.getenv('DB_USER')
        DATABSE_PASSWORD = os.getenv('DB_PASSWORD')
        DATABASE_HOST = os.getenv('DB_HOST')
        DATABSE_PORT = os.getenv('DB_PORT')
        os.system("PGPASSWORD="+ DATABSE_PASSWORD + " pg_restore -h " + DATABASE_HOST + " -U " + DATABSE_USER + " -d " + DATABASE_NAME + " -t account_partner_history_set -a -F t ./apps/account/migrations/partner_history.tar -v")

    def doNothing(apps, schema_editor):
        pass

    dependencies = [
        ('account', '0037_createpartnerhistory_20210115_1531'),
    ]

    operations = [
        # migrations.RunPython(restore, reverse_code= doNothing),
        # migrations.RunSQL(
        #     sql = ['SELECT * FROM account_partner_history_set WHERE id=1'],
        #     reverse_sql = ['DELETE FROM account_partner_history_set']),
    ]
