# Generated by Django 3.0.8 on 2021-01-14 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('account', '0038_restorepartnerhistory_20210115_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Partner')),
            ],
            options={
                'verbose_name_plural': '파트너카테고리',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='mainField',
            field=models.ManyToManyField(related_name='history_product', through='account.PartnerCategory', to='category.Category', verbose_name='의뢰 가능한 분야'),
        ),
    ]
