# Generated by Django 3.0.8 on 2021-01-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_partnerCategory_20210114_1146'),
    ]

    operations = [
        migrations.RunSQL(
            sql = ['INSERT INTO account_partnercategory (partner_id,category_id) SELECT partner_id,category_id FROM account_partner_history_set LEFT JOIN category_subclass ON account_partner_history_set.subclass_id = category_subclass.id;'],
            reverse_sql = ['DELETE FROM account_partnercategory']),
    ]
