# Generated by Django 3.0.8 on 2021-01-26 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_user_showpassword_20210118_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category'),
        ),
    ]
