# Generated by Django 3.0.8 on 2021-01-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_add_random_partnercategory_20210126_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=256, null=True, verbose_name='이메일'),
        ),
    ]
