# Generated by Django 3.0.8 on 2021-02-04 08:31

from django.db import migrations
from dotenv import load_dotenv
import os
load_dotenv()
partner_id_to_delete_logo = "('32', '775', '53', '452', '45', '51', '425', '164', '169', '809', '161', '162', '660', '165', '731', '784', '811', '813', '41', '778', '168', '37', '273', '48', '426', '709', '714', '416', '801', '412', '785', '777', '44', '31', '34', '36', '40', '136', '761', '38', '730', '794', '703', '790', '329', '384', '42', '330', '754', '793', '702', '182', '700', '691', '738', '194', '799', '730', '37', '36', '777', '778', '784', '794', '801', '809', '123', '775', '811', '194', '813', '169', '168', '165', '7814', '164', '221', '7815', '754', '713', '167', '785', '242', '133', '162', '161', '136', '273', '330', '329', '333', '384', '426', '425', '422', '416', '412', '660', '715', '732', '116')"

class Migration(migrations.Migration):
    def backup (apps, schema_editor):
        DATABASE_NAME = os.getenv('DB_NAME')
        DATABSE_USER = os.getenv('DB_USER')
        DATABSE_PASSWORD = os.getenv('DB_PASSWORD')
        DATABASE_HOST = os.getenv('DB_HOST')
        DATABSE_PORT = os.getenv('DB_PORT')
        os.system("PGPASSWORD=" + DATABSE_PASSWORD + " pg_dump -h " + DATABASE_HOST + " -U " + DATABSE_USER + " -d boltnnutplatform2 -t account_partner -F t -f ./apps/account/migrations/partner_history.tar -v")

    dependencies = [
        ('account', '0046_remove_user_showpassword'),
    ]

    sqlCache = """
        update "account_partner"
        set 
            logo = 'null'
        where id in {data}
    """.format(data = partner_id_to_delete_logo)
    
    operations = [
        migrations.RunPython(backup, reverse_code = migrations.RunPython.noop),
        migrations.RunSQL(
            sql = sqlCache,
            reverse_sql = migrations.RunSQL.noop
        )
    ]
