# Generated by Django 3.0.8 on 2021-02-04 09:56

from django.db import migrations


class Migration(migrations.Migration):
    partner_id_to_delete_logo = "('102','39','710','708','729','705','712','701','716','728','707', '711', '229', '30', '226')" 
    dependencies = [
        ('account', '0047_remove_pratner_logo_20210204_1731'),
    ]

    sqlCache = """
        update "account_partner"
        set 
            logo = 'null'
        where id in {data}
    """.format(data = partner_id_to_delete_logo)
    
    operations = [
        migrations.RunSQL(
            sql = sqlCache,
            reverse_sql = migrations.RunSQL.noop
        )
    ]