# Generated by Django 3.0.8 on 2021-02-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_setstringnull_20210204_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.CharField(max_length=256, null=True, verbose_name='부서'),
        ),
        migrations.AddField(
            model_name='client',
            name='realName',
            field=models.CharField(max_length=256, null=True, verbose_name='이름'),
        ),
    ]
