# Generated by Django 3.0.8 on 2021-02-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_change_partner_logo_20210210_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='history_set',
        ),
    ]
