# Generated by Django 3.0.8 on 2021-04-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='grade',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
