# Generated by Django 3.0.8 on 2021-04-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20210219_1901'),
        ('account', '0054_auto_20210413_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientclass',
            name='client',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partner_estimate',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnercategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='partnercategory',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='process',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='career',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='info_biz',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='region',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='revenue',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Clientclass',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Partner_Estimate',
        ),
        migrations.DeleteModel(
            name='PartnerCategory',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
