# Generated by Django 3.0.8 on 2021-04-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_auto_20210414_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='mainField',
        ),
    ]
