# Generated by Django 3.0.8 on 2021-05-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_partnerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerReviewTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnername', models.CharField(max_length=256, null=True, verbose_name='업체명')),
                ('score', models.IntegerField(choices=[(1, '매우 불만족'), (2, '불만족'), (3, '보통'), (4, '만족'), (5, '매우 만족')], default=0, verbose_name='점수')),
                ('content', models.CharField(max_length=256, null=True, verbose_name='컨텐츠')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='클라이언트')),
            ],
            options={
                'verbose_name': '점수',
                'verbose_name_plural': '점수',
            },
        ),
    ]
