# Generated by Django 3.0.8 on 2021-05-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_auto_20210517_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, null=True, verbose_name='검색어')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검색일자')),
            ],
            options={
                'verbose_name': '검색어',
                'verbose_name_plural': '검색어',
            },
        ),
    ]
