# Generated by Django 3.0.8 on 2021-06-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_searchtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchText',
        ),
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
