# Generated by Django 3.0.8 on 2021-06-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_searchtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
