# Generated by Django 3.0.8 on 2021-06-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_delete_loginlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchText',
        ),
    ]
