# Generated by Django 3.0.8 on 2020-11-07 07:37

import apps.estimate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stp_file', models.FileField(upload_to=apps.estimate.models.stp_update_filename, verbose_name='stp파일')),
                ('stl_file', models.FileField(upload_to=apps.estimate.models.stl_update_filename, verbose_name='stl파일')),
                ('volume', models.FloatField(verbose_name='부피')),
                ('x_length', models.FloatField(verbose_name='x축 길이')),
                ('y_length', models.FloatField(verbose_name='y축 길이')),
                ('z_length', models.FloatField(verbose_name='z축 길이')),
                ('created_at', models.DateTimeField(default=apps.estimate.models.time, verbose_name='등록일자')),
            ],
            options={
                'verbose_name': '     가견적 내역',
                'verbose_name_plural': '     가견적 내역',
            },
        ),
    ]
