# Generated by Django 3.0.8 on 2020-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='종류'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='material',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='재질'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='maximumPrice',
            field=models.FloatField(default=0, verbose_name='사출가 최대가격'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='minimumPrice',
            field=models.FloatField(default=0, verbose_name='사출가 최소가격'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='moldedMaximumPrice',
            field=models.FloatField(default=0, verbose_name='금형가 최대가격'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='moldedMinimumPrice',
            field=models.FloatField(default=0, verbose_name='금형가 최소가격'),
        ),
    ]
