# Generated by Django 3.0.8 on 2021-01-21 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_auto_20201207_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailManufactureProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='공정명')),
                ('minShoot', models.IntegerField(verbose_name='쇼트 최소값')),
                ('maxShoot', models.IntegerField(verbose_name='쇼트 최대값')),
                ('minPostProcessing', models.IntegerField(verbose_name='후가공게이트사상 최소값')),
                ('maxPostProcessing', models.IntegerField(verbose_name='후가공게이트사상 최대값')),
            ],
            options={
                'verbose_name': '     세부 공정',
                'verbose_name_plural': '     세부 공정',
            },
        ),
        migrations.CreateModel(
            name='manufactureProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='공정명')),
            ],
            options={
                'verbose_name': '     공정 대분류',
                'verbose_name_plural': '     공정 대분류',
            },
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='재료명')),
                ('price', models.FloatField(verbose_name='가격')),
                ('detailProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.detailManufactureProcess', verbose_name='세부공정')),
            ],
            options={
                'verbose_name': '     재료',
                'verbose_name_plural': '     재료',
            },
        ),
        migrations.AddField(
            model_name='detailmanufactureprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.manufactureProcess', verbose_name='공정 대분류'),
        ),
    ]
