# Generated by Django 3.0.8 on 2021-01-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0003_process_create_20210121_1044'),
    ]

    processCache =[
        '금형사출',
        '3D 프린팅',
        'CNC'
    ]

    processDetailCache = [
        [
            {'name': '플라스틱', 'minShoot': 72, 'maxShoot': 100, 'minPostProcessing': 10, 'maxPostProcessing': 20},
            {'name': '실리콘', 'minShoot': 70, 'maxShoot': 100, 'minPostProcessing': 0, 'maxPostProcessing': 0},   
        ],
        [
            {'name': '기본', 'minShoot': 0, 'maxShoot': 0, 'minPostProcessing': 0, 'maxPostProcessing': 0}
        ],
        [
            {'name':'기본', 'minShoot': 0, 'maxShoot': 0, 'minPostProcessing': 0, 'maxPostProcessing': 0}
        ]        
    ]

    materialCache = [
        {'detailName': '플라스틱', 'materialName': 'ABS', 'price': 3.6},
        {'detailName': '실리콘', 'materialName': '일반실리콘', 'price': 7},
    ]

    sqlCache = []
    
    for process in processCache:
        sqlCache.append(
            """ 
                insert into "estimate_manufactureprocess"
                ("name")
                values('{process}');
            """.format(process = process)
        )

    for processIndex in range(len(processCache)):
        for detailProcess in processDetailCache[processIndex]:
            sqlCache.append(
                """ 
                    insert into "estimate_detailmanufactureprocess"
                    ("name", "minShoot", "maxShoot", "minPostProcessing", "maxPostProcessing", "process_id")
                    values(
                        '{detailProcessName}',
                        '{minShoot}',
                        '{maxShoot}',
                        '{minPostProcessing}',
                        '{maxPostProcessing}',
                        (   
                            select id 
                            from "estimate_manufactureprocess" 
                            where name = '{processName}'
                        )
                    );
                """.format(
                        detailProcessName = detailProcess['name'], 
                        minShoot = detailProcess['minShoot'],
                        maxShoot = detailProcess['maxShoot'],
                        minPostProcessing = detailProcess['minPostProcessing'],
                        maxPostProcessing = detailProcess['maxPostProcessing'],
                        processName = processCache[processIndex]                    
                    )
            )

    for material in materialCache:
        sqlCache.append(
            """
                insert into "estimate_material"
                ("name", "price", "detailProcess_id")
                values(
                    '{materialName}',
                    '{price}',
                    (
                        select id 
                        from "estimate_detailmanufactureprocess"
                        where name = '{detailName}'
                    )
                )
            """.format(materialName = material['materialName'], price = material['price'], detailName = material['detailName'])
        )





    reverseSqlCache = []

    for process in processCache:
        reverseSqlCache.append(
            """ 
                delete from "estimate_material";
                delete from "estimate_detailmanufactureprocess";
                delete from "estimate_manufactureprocess";
            """
        )

    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )        
    ]
