# Generated by Django 3.0.8 on 2021-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0004_process_data_20210121_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name="estimate",
            old_name="maximumPrice",
            new_name="maxPrice",
        ),
        migrations.AlterField(
            model_name='estimate',
            name='maxPrice',
            field=models.FloatField(default=0, verbose_name='최대가격'),
        ),

        migrations.RenameField(
            model_name= 'estimate',
            old_name= 'minimumPrice',
            new_name = 'minPrice'
        ),
        migrations.AlterField(
            model_name='estimate',
            name='minPrice',
            field=models.FloatField(default=0, verbose_name='최소가격'),
        ),


        migrations.RenameField(
            model_name="estimate",
            old_name="moldedMaximumPrice",
            new_name="totalMaxPrice",
        ),
        migrations.AlterField(
            model_name="estimate",
            name="totalMaxPrice",
            field=models.FloatField(default=0, verbose_name='수수료 포함 최대 가격'),
        ),

        migrations.RenameField(
            model_name="estimate",
            old_name="moldedMinimumPrice",
            new_name="totalMinPrice",
        ),
        migrations.AlterField(
            model_name="estimate",
            name="totalMinPrice",
            field=models.FloatField(default=0, verbose_name='수수료 포함 최소 가격'),
        )

    ]
