# Generated by Django 3.0.8 on 2021-01-22 02:13

from django.db import migrations, models
import django.db.models.deletion
from dotenv import load_dotenv
import os
load_dotenv()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_add_token_20210120_1225'),
        ('estimate', '0005_estimate_alter_20210122_1043'),
    ]
    def backup (apps, schema_editor):
        DATABASE_NAME = os.getenv('DB_NAME')
        DATABSE_USER = os.getenv('DB_USER')
        DATABSE_PASSWORD = os.getenv('DB_PASSWORD')
        DATABASE_HOST = os.getenv('DB_HOST')
        DATABSE_PORT = os.getenv('DB_PORT')
        os.system("PGPASSWORD=" + DATABSE_PASSWORD + " pg_dump -Fc -h " + DATABASE_HOST + " -U " + DATABSE_USER + " -d " + DATABASE_NAME + " -f ./apps/account/migrations/0035_client_data_20210107_1155_backup.tar -v")

    
    operations = [
        migrations.RunPython(backup, reverse_code= migrations.RunPython.noop),
        migrations.RunSQL(
            sql = ["""TRUNCATE  "estimate_estimate"; """],
            reverse_sql = migrations.RunSQL.noop
        ),
        migrations.AddField(
            model_name='estimate',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.Request', verbose_name='의뢰서', null = True),
        )
    ]
