# Generated by Django 3.0.8 on 2021-01-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0006_estimate_add_20210122_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='totalMinPrice',
            field=models.FloatField(default=0, verbose_name='수수료 포함 최소 가격 '),
        ),
    ]
