# Generated by Django 3.0.8 on 2021-02-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0007_estimate_alter_20210122_1329'),
    ]
    
    sqlCache = [
        """
            insert into public.estimate_detailmanufactureprocess
            ("name", "minShoot", "maxShoot", "minPostProcessing", "maxPostProcessing", "process_id")
            values(
                'FDM',
                0,
                0,
                0,
                0,
                (select id from estimate_manufactureprocess
                where name = '3D 프린팅')
            )
        """,
        """
            insert into public.estimate_detailmanufactureprocess
            ("name", "minShoot", "maxShoot", "minPostProcessing", "maxPostProcessing", "process_id")
            values(
                'SLA',
                0,
                0,
                0,
                0,
                (select id from estimate_manufactureprocess
                where name = '3D 프린팅')
            )
        """,
        """
            insert into public.estimate_detailmanufactureprocess
            ("name", "minShoot", "maxShoot", "minPostProcessing", "maxPostProcessing", "process_id")
            values(
                '비금속',
                0,
                0,
                0,
                0,
                (select id from estimate_manufactureprocess
                where name = 'CNC')
            )
        """,
        """
            insert into public.estimate_detailmanufactureprocess
            ("name", "minShoot", "maxShoot", "minPostProcessing", "maxPostProcessing", "process_id")
            values(
                '금속',
                0,
                0,
                0,
                0,
                (select id from estimate_manufactureprocess
                where name = 'CNC')
            )
        """,
        """
            insert into estimate_material
            ("name", "price", "detailProcess_id")
            values(
                '3D 프린팅 SLA 기본 재료',
                0,
                (
                    select id from estimate_detailmanufactureprocess
                    where name = 'SLA'
                )	
            )
        """,
        """
            insert into estimate_material
            ("name", "price", "detailProcess_id")
            values(
                '3D 프린팅 FDM 기본 재료',
                0,
                (
                    select id from estimate_detailmanufactureprocess
                    where name = 'FDM'
                )	
            )
        """,
        """
            insert into estimate_material
            ("name", "price", "detailProcess_id")
            values(
                'CNC 금속 기본 재료',
                0,
                (
                    select id from estimate_detailmanufactureprocess
                    where name = '금속'
                )	
            )
        """,
        """
            insert into estimate_material
            ("name", "price", "detailProcess_id")
            values(
                'CNC 비금속 기본 재료',
                0,
                (
                    select id from estimate_detailmanufactureprocess
                    where name = '비금속'
                )	
            )
        """

    ]

    reverseSqlCache = [
        """
            delete from estimate_material
            where name = '3D 프린팅 SLA 기본 재료' or name ='3D 프린팅 FDM 기본 재료' or name = 'CNC 금속 기본 재료' or name = 'CNC 비금속 기본 재료'
        """,

        """
            delete from estimate_detailmanufactureprocess
            where 
                name = 'SLA' 
                and process_id = 
                (
                    select id 
                    from estimate_manufactureprocess
                    where name = '3D 프린팅'
                )
        """,
        """
            delete from estimate_detailmanufactureprocess
            where 
                name = 'FDM' 
                and process_id = 
                (
                    select id 
                    from estimate_manufactureprocess
                    where name = '3D 프린팅'
                )
        """,
        """
            delete from estimate_detailmanufactureprocess
            where 
                name = '금속' 
                and process_id = 
                (
                    select id 
                    from estimate_manufactureprocess
                    where name = 'CNC'
                )
        """,
        """
            delete from estimate_detailmanufactureprocess
            where 
                name = '비금속' 
                and process_id = 
                (
                    select id 
                    from estimate_manufactureprocess
                    where name = 'CNC'
                )
        """
    ]
    operations = [
        migrations.RunSQL (
            sql = sqlCache,
            reverse_sql= reverseSqlCache
        )
    ]
