# Generated by Django 3.0.8 on 2021-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0010_estimate_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='number',
            field=models.IntegerField(default=1, verbose_name='수량'),
            preserve_default=False,
        ),
    ]
