# Generated by Django 3.0.8 on 2021-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0011_estimate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='수량'),
        ),
    ]
