# Generated by Django 3.0.8 on 2021-06-09 07:09

import apps.estimate.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_searchtext'),
        ('estimate', '0012_auto_20210430_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='clickLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=256, null=True, verbose_name='검색어')),
                ('created_at', models.DateTimeField(default=apps.estimate.models.time, verbose_name='등록일자')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='작성클라이언트')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Partner', verbose_name='파트너')),
            ],
            options={
                'verbose_name': '     클릭로그',
                'verbose_name_plural': '     클릭로그',
            },
        ),
    ]
