# Generated by Django 3.0.8 on 2021-06-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0013_clicklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clickLog',
        ),
    ]
