# Generated by Django 3.0.8 on 2021-06-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0013_clicklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicklog',
            name='search',
            field=models.CharField(max_length=256, null=True, verbose_name='검색어'),
        ),
    ]
