# Generated by Django 3.0.8 on 2021-06-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0014_auto_20210609_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clickLog',
        ),
    ]
