# Generated by Django 3.0.8 on 2021-02-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': 'BigCategory',
                'verbose_name_plural': 'BigCategorys',
            },
        ),
        migrations.CreateModel(
            name='MiddleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='카테고리명')),
                ('bigCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcategory.BigCategory')),
            ],
            options={
                'verbose_name': 'MiddleCategory',
                'verbose_name_plural': 'MiddleCategorys',
            },
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='카테고리명')),
                ('middleCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcategory.MiddleCategory')),
            ],
            options={
                'verbose_name': 'SmallCategory',
                'verbose_name_plural': 'SmallCategorys',
            },
        ),
    ]
