# Generated by Django 3.0.8 on 2021-02-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210218_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylist',
            name='count',
            field=models.IntegerField(default=0, verbose_name='개수'),
        ),
    ]
