# Generated by Django 3.0.8 on 2021-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210218_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylist',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name='개수'),
        ),
    ]
