# Generated by Django 3.0.8 on 2021-01-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailQuestion', '0001_initial'),
    ]
    questionList = [
        '제작하고자 하는 제품은 어떤 제품인가요?',
        '제품은 어떤 소재인가요?',
        '생산을 위한 도면 파일이 있나요?',
        '도면을 첨부해주시면 생산 가견적을 안내드립니다',
        '전자 제품인가요?',
        '개발이 필요한가요?',
        '방수/내열 설계가 필요하거나 제품에 힘이 가해져 내구성을 고려한 설계가 필요한가요'
    ]
    sqlCache = []
    reverseSqlCache = []
    for question in questionList:
        sqlCache.append(
            """
                insert into public."detailQuestion_detailquestiontitle"
                ("question", "createdAt")
                values(
                    '{question}',
                    now()
                );
            """.format(question = question)
        )

        reverseSqlCache.append(
            """
                delete from public."detailQuestion_detailquestiontitle";
                ALTER SEQUENCE "detailQuestion_detailquestiontitle_id_seq" RESTART WITH 1;
            """
        )



    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
