# Generated by Django 3.0.8 on 2021-01-14 04:39

from django.db import migrations
from ..models import *
import os
import sys
sys.path.append(
    os.path.dirname(os.path.abspath(
        os.path.dirname(os.path.abspath(
            os.path.dirname(os.path.abspath(
                __file__
            ))
        ))
    ))
)
from api.detailQuestion.serializers import *
class Migration(migrations.Migration):

    dependencies = [
        ('detailQuestion', '0003_detailQuestion_add_20210114_1146'),
    ]

    sqlCache = []
    reverseSqlCache = []
    
    titleList = [
        '제작하고자 하는 제품은 어떤 제품인가요?',
        '제품은 어떤 소재인가요?',
        '생산을 위한 도면 파일이 있나요?',
        '도면을 첨부해주시면 생산 가견적을 안내드립니다',
        '전자 제품인가요?',
        '개발이 필요한가요?',
        '방수/내열 설계가 필요하거나 제품에 힘이 가해져 내구성을 고려한 설계가 필요한가요'
    ]
    titleIdList = [1, 2, 3, 4, 5, 6, 7]
    # for title in titleList:
    #     titleCache = DetailQuestionTitle.objects.get(question = title)
    #     titleSerializered = DetailQuestionTitleSerializer(titleCache).data
    #     titleIdList.append(titleSerializered[ 'id' ])
    selectList = [
        [
            ['시중에 판매되는 제품 그대로 개발', titleIdList[1] ], 
            ['시중에 판매되는 제품 디자인 변경 개발',titleIdList[1]],
            ['시중에 판매되는 제품의 기능 변경 개발',titleIdList[1]],
            ['기존 제품이 없는 신제품 개발', titleIdList[1]]
        ],
        [
            ['금속류', titleIdList[2]],
            ['실리콘/고무', titleIdList[2]],
            ['플라스틱',  titleIdList[2]],
            ['이외 기타',  titleIdList[2]],
        ],
        [
            ['예',  titleIdList[3]],
            ['아니요',  titleIdList[4]],
        ],
        [
            ['적합한 도면이 없습니다.',titleIdList[4]]

        ],
        [
            ['예', titleIdList[5]],
            ['아니요', titleIdList[6]],
        ],
        [
            ['Web 개발 필요', 'null'],
            ['App(IoT 개발)', 'null'],
            ['서버 개발', 'null'],
            ['불필요함', 'null'],
        ],
        [
            ['예', 'null'],
            ['아니요', 'null'],
        ],
    ]
    for index in range( len(titleIdList) ):
        for select in selectList[index]:
            sqlCache.append(
                """
                    insert into public."detailQuestion_detailquestionselect"
                    ("select", "createdAt", "title_id", "nextTitle_id")
                    values(
                        '{select}',
                        now(),
                        '{titleId}',
                        {nextId}
                    );
                """.format(select = select[0], titleId = titleIdList[index], nextId = select[1])
            )        
    
    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = ['delete from public."detailQuestion_detailquestionselect";']
        )
    ]
